### ISSUE TITLE
Don't run kernel config check when the role is skipped

### ISSUE THREAD

**Issue by Yoda-BZH** [ansibleguy/infra_nftables#2]
I'm trying to apply a limited set of roles with `ansible-playbook -i inventory.yml -l myservername --tags whatever main.yml -K`

The selected tag `whatever` is unrelated to infra_nftables.

However, the following tags are **always** ran:
* NFTables | Checking config https://github.com/ansibleguy/infra_nftables/blob/004b84a2cec37d773efc0b5c5f9d97b50a7b6e28/tasks/main.yml#L6-L14
* NFTables | Check | Checking kernel config https://github.com/ansibleguy/infra_nftables/blob/004b84a2cec37d773efc0b5c5f9d97b50a7b6e28/tasks/check_debian_kernel_config.yml#L17-L23

The last step is failing as `nft_kernel_config.stdout_lines` is defined in  `NFTables | Check | Pulling kernel config`, which is not always ran https://github.com/ansibleguy/infra_nftables/blob/004b84a2cec37d773efc0b5c5f9d97b50a7b6e28/tasks/check_debian_kernel_config.yml#L3-L15

Can the dependency be fixed please ?

Thank you

**Comment by ansibleguy** [comment]
Greetings @Yoda-BZH 
I've removed the `always` tags and replaced them with the role-specific ones.
