### ISSUE TITLE
Kernel check should check for modules too

### ISSUE THREAD

**Issue by Yoda-BZH** [ansibleguy/infra_nftables#4]
In https://github.com/ansibleguy/infra_nftables/blob/004b84a2cec37d773efc0b5c5f9d97b50a7b6e28/tasks/check_debian_kernel_config.yml#L17-L23

Only inline dependencies are check. In some Ubuntu version (18.04), those dependencies are in modules:
```
# grep NF_TABLES_INET /boot/config-$(uname -r)
CONFIG_NF_TABLES_INET=m
```

Can the check checks for modules too ?

Something like
```
      - "'CONFIG_NF_TABLES_INET=y' in nft_kernel_config.stdout_lines or 'CONFIG_NF_TABLES_INET=m' in nft_kernel_config.stdout_lines"
      - "'CONFIG_NF_TABLES_IPV4=y' in nft_kernel_config.stdout_lines or 'CONFIG_NF_TABLES_IPV4=m' in nft_kernel_config.stdout_lines"
```

Thank you

**Comment by ansibleguy** [comment]
Greetings @Yoda-BZH 

Thanks for the info.
Please test the fix and report back if it still makes problems.
